version: '3.9'
# run docker swarm init && docker stack deploy -c docker-stack.yaml
services:
  caddy:
    image: registry.digitalocean.com/fdcr/filing-deadlines/frontend:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "3002:3002"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_PORT: 3000
    env_file:
      - .url.env
    logging:
      driver: local
  redis:
    image: redis/redis-stack-server
    volumes:
      - redisdata:/data
    logging:
      driver: local
  worker:
    image: registry.digitalocean.com/fdcr/filing-deadlines/backend:latest
    working_dir: /filing-deadlines/worker
    environment:
      REDIS_URL: redis://redis:6379
      LOKI_URL: "http://loki:3100"
    env_file:
      - .api.env
    logging:
      driver: local
    depends_on:
      - redis
  server:
    image: registry.digitalocean.com/fdcr/filing-deadlines/backend:latest
    working_dir: /filing-deadlines/server
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3000
      LOKI_URL: "http://loki:3100"
    env_file:
      - .api.env
      - .xero.env
      - .auth0.env
      - .server.env
      - .url.env
      - .stripe.env
    logging:
      driver: local
    depends_on:
      - redis
  "metrics":
    image: registry.digitalocean.com/fdcr/filing-deadlines/metrics:latest
    logging:
      driver: local
    "environment":
      "CADDY_METRICS_URL": "http://caddy:2022"
    "volumes":
      - "prom_data:/prometheus"
  "loki":
    image: registry.digitalocean.com/fdcr/filing-deadlines/loki:latest
    logging:
      driver: local
    "volumes":
      - "loki_data:/loki"
  "grafana":
    image: registry.digitalocean.com/fdcr/filing-deadlines/grafana:latest
    logging:
      driver: local
    "volumes":
      - "grafana_data:/var/lib/grafana"
      - "/var/log/grafana"
    "environment":
      LOKI_URL: "http://loki:3100"
      METRICS_URL: "http://metrics:9090"
  repl:
    image: registry.digitalocean.com/fdcr/filing-deadlines/backend:latest
    command: tail -f /dev/null
    working_dir: /filing-deadlines/repl
    depends_on:
      - redis
    "environment":
      REDIS_URL: redis://redis:6379
      LOKI_URL: "http://loki:3100"

volumes:
  redisdata:
  caddy_data:
  caddy_config:
  grafana_data:
  loki_data:
  prom_data:
