version: '3.9'
# this docker compose is for building all the images during development. This was the previous way of running the project.
services:
  caddy:
    build:
      dockerfile: Frontend.Dockerfile
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "3002:3002"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_PORT: 3000
    env_file:
      - .url.env
    logging:
      driver: local
    depends_on:
      - server # server must be running already to allow health check to pass
  redis:
    image: redis/redis-stack-server
    volumes:
      - redisdata:/data
    logging:
      driver: local
  worker:
    build:
      dockerfile: Backend.Dockerfile
    working_dir: /filing-deadlines/worker
    environment:
      REDIS_URL: redis://redis:6379
      LOKI_URL: "http://loki:3100"
    env_file:
      - .api.env
    logging:
      driver: local
    depends_on:
      - redis
  server:
    build:
      dockerfile: Backend.Dockerfile
    working_dir: /filing-deadlines/server
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3000
      LOKI_URL: "http://loki:3100"
    env_file:
      - .api.env
      - .xero.env
      - .server.env
      - .url.env
      - .stripe.env
    logging:
      driver: local
    depends_on:
      - redis
      - loki
  "metrics":
    build:
      context: monitoring/prometheus
    logging:
      driver: local
    "environment":
      "CADDY_METRICS_URL": "http://caddy:2022"
    "volumes":
      - "prom_data:/prometheus"
  "loki":
    build:
      context: monitoring/loki
    logging:
      driver: local
    "volumes":
      - "loki_data:/loki"
  "grafana":
    build:
      context: monitoring/grafana
    logging:
      driver: local
    "volumes":
      - "grafana_data:/var/lib/grafana"
      - "/var/log/grafana"
    "environment":
      LOKI_URL: "http://loki:3100"
      METRICS_URL: "http://metrics:9090"
  repl:
    build:
      dockerfile: Backend.Dockerfile
    command: node index.js
    working_dir: /filing-deadlines/repl
    depends_on:
      - redis
    "environment":
      REDIS_URL: redis://redis:6379
      LOKI_URL: "http://loki:3100"
    tty: true
    stdin_open: true

volumes:
  redisdata:
  caddy_data:
  caddy_config:
  grafana_data:
  loki_data:
  prom_data:
