{
 "title": "Navigations",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of client side navigations",
   "type": "timeseries",
   "description": "Count over time of client side navigations",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(url_path) (count_over_time({component=\"server\"} |= `Client side navigation to` | json | component_extracted = `client` [$__interval]))"
    }
   ]
  },
  {
   "title": "Navigation logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `Client side navigation to` | json | component_extracted = `client` | line_format `{{.msg}} {{.url_search}} {{.url_hash}}`"
    }
   ]
  },
  {
   "title": "Visibility logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `Client side visibility state changed` | json | component_extracted = `client` | line_format `{{.msg}}     {{.userAgent}}`"
    }
   ]
  }
 ]
}