{
 "title": "RequestsAndResponseRate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(req_method) (count_over_time({component=\"server\"} |= `incoming request` | json [$__interval]))",
     "legendFormat": "{{req_method}}"
    }
   ]
  },
  {
   "title": "Responses by code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(res_statusCode) (count_over_time({component=\"server\"} |= `request completed` | json [$__interval]))",
     "legendFormat": "{{req_method}}"
    }
   ]
  },
  {
   "title": "Responses by duration",
   "type": "timeseries",
   "description": "Response time of requests as measured by fastify",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time({component=\"server\"} |= `request completed` | json duration=\"responseTime\" | unwrap duration [$__interval])",
     "legendFormat": "{{component}} {{hostname}}"
    }
   ]
  }
 ]
}