{
 "title": "ServerLogs",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Count of logs by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(level) (count_over_time({component=\"server\"} | json [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "description": "Other logs from server component apart from incoming and completed requests, formatted by user and org on session of request.",
   "gridPos": { "h": 32, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"server\"} != `incoming request` != `request completed` | json | line_format `{{.level}} {{.reqId}} user={{if .userId}}true {{else}}false{{end}} org={{if .orgId}}true {{else}}false{{end}}   {{.msg}}`"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "logs",
   "description": "Incoming request logs from fastify server",
   "gridPos": { "h": 32, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `incoming request` | json | line_format `{{.level}} {{.reqId}} {{.req_method}} {{ .req_url | trunc 60 }}`"
    }
   ]
  },
  {
   "title": "Requests completed",
   "type": "logs",
   "description": "Outgoing reply logs from fastify server",
   "gridPos": { "h": 32, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `request completed` | json | line_format `{{.level}} {{.reqId}} CODE {{.res_statusCode}} in {{round .responseTime 2}}ms`"
    }
   ]
  }
 ]
}