{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `incoming request` | json | line_format `{{.level}} {{.reqId}} {{.msg}} {{.req_method}} {{.req_url}}`"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"server\"} |= `request completed` | json | line_format `{{.level}} {{.reqId}} Response time: {{round .responseTime 2}}ms`"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{component=\"server\"} | json | line_format `{{.level}} {{.reqId}} {{.msg}}`"
    }
   ]
  }
 ]
}