global:
  scrape_interval: 15s
scrape_configs:
  - job_name: caddy
    static_configs:
      - targets:
          - caddy:2022
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
