{
 "title": "CaddyRequests",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Caddy Uptime",
   "type": "status-history",
   "description": "Hasn't been tested to show downtime correctly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "File server requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"file_server\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverse proxy requests per second",
   "type": "gauge",
   "description": "Includes grafana",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"reverse_proxy\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics requests per second",
   "type": "gauge",
   "description": "Prometheus",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second to static file server",
   "type": "timeseries",
   "description": "Caddy metrics of total requests to file_server. Doesn't include API endpoints.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"file_server\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Requests per second to reverse proxy",
   "type": "timeseries",
   "description": "Caddy metrics of total requests to reverse_proxy. Unfortunately includes grafana traffic as well. Not sure how to avoid this.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{handler=\"reverse_proxy\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "barchart",
   "description": "To reverse proxy, includes grafana. Numbers aren't accurate",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(method) (rate(caddy_http_request_duration_seconds_sum{handler=\"reverse_proxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}