{
 "title": "CaddyStatuses",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jobs down",
   "type": "timeseries",
   "description": "Shows a bar when a prometheus monitored job is down",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count by(job) (up == 0)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Upstream statuses",
   "type": "status-history",
   "description": "Whether the upstreams that caddy is proxying are healthy or not.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{job=\"caddy\"}",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Up status",
   "type": "status-history",
   "description": "Whether caddy and loki is up. Assumes up if prometheus goes down.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}