name: 'build-typescript'
on: # rebuild any PRs and any branch changes
  pull_request:
  push:
#todo: would be good to spin up the server and request a health status endpoint, to ensure that all fastify plugins could register.
# For example regex schema mistakes are only caught when the plugin registers, not in typescript compile.
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build server typescript
        run: pnpm run build
        working-directory: server
      - name: Build worker typescript
        run: pnpm run build
        working-directory: worker
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build client with Vite
        run: pnpm run build
        working-directory: client
