name: 'Build client'
on: # rebuild any PRs and any branch changes
  pull_request:
  push:
    paths:
      - 'client/**'
      - 'fs-shared/**'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.12.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - run: echo "~~~" >> $GITHUB_STEP_SUMMARY
      - name: Build client with Vite
        run: pnpm run build >> $GITHUB_STEP_SUMMARY
        working-directory: client
        env:
          NO_COLOR: 1
      - run: echo "~~~" >> $GITHUB_STEP_SUMMARY
