name: 'Build and push monitoring docker images'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'monitoring'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com/fdcr
          username: ${{ secrets.CR_TOKEN }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push metrics
        id: docker-build-metrics
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/fdcr/filing-deadlines/metrics:latest
          context: monitoring/prometheus
      - name: Build and push grafana
        id: docker-build-grafana
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/fdcr/filing-deadlines/grafana:latest
          context: monitoring/grafana
      - name: Build and push loki
        id: docker-build-loki
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/fdcr/filing-deadlines/loki:latest
          context: monitoring/loki

      - name: "Print summaries"
        run: |
          echo "# Docker build and push summaries" >> $GITHUB_STEP_SUMMARY
          echo "## Metrics" >> $GITHUB_STEP_SUMMARY
          echo "Image ID: ${{ steps.docker-build-metrics.outputs.imageid }}"  >> $GITHUB_STEP_SUMMARY
          echo "Digest: ${{ steps.docker-build-metrics.outputs.digest }}"  >> $GITHUB_STEP_SUMMARY
          echo "Metadata: ${{ toJSON(fromJSON(steps.docker-build-metrics.outputs.metadata)) }}"  >> $GITHUB_STEP_SUMMARY
          echo "## Grafana" >> $GITHUB_STEP_SUMMARY
          echo "Image ID: ${{ steps.docker-build-grafana.outputs.imageid }}"  >> $GITHUB_STEP_SUMMARY
          echo "Digest: ${{ steps.docker-build-grafana.outputs.digest }}"  >> $GITHUB_STEP_SUMMARY
          echo "Metadata: ${{ toJSON(fromJSON(steps.docker-build-grafana.outputs.metadata)) }}"  >> $GITHUB_STEP_SUMMARY
          echo "## Loki" >> $GITHUB_STEP_SUMMARY
          echo "Image ID: ${{ steps.docker-build-loki.outputs.imageid }}"  >> $GITHUB_STEP_SUMMARY
          echo "Digest: ${{ steps.docker-build-loki.outputs.digest }}"  >> $GITHUB_STEP_SUMMARY
          echo "Metadata: ${{ toJSON(fromJSON(steps.docker-build-loki.outputs.metadata)) }}"  >> $GITHUB_STEP_SUMMARY

