name: 'Build and push docker images'

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com/fdcr
          username: ${{ secrets.CR_TOKEN }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.digitalocean.com/fdcr/filing-deadlines/backend:latest
          file: Backend.Dockerfile
      - name: "Print summary"
        run: |
          echo "# Docker build and push summary" >> $GITHUB_STEP_SUMMARY
          echo "Image ID: ${{ steps.docker-build.imageid }}"  >> $GITHUB_STEP_SUMMARY
          echo "Digest: ${{ steps.docker-build.digest }}"  >> $GITHUB_STEP_SUMMARY
#          echo "Metadata: ${{ toJSON(fromJSON(steps.docker-build.metadata)) }}"  >> $GITHUB_STEP_SUMMARY

