name: 'Light house scores'
on: # rebuild any PRs and any branch changes
  pull_request:
  push:
    paths:
      - client/**
      - fs-shared/**
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build client with Vite
        run: pnpm run build
        working-directory: client
      - id: lighthouse-step
        name: Run Lighthouse against built client
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: '.github/lighthouse/lighthouserc.json'
          runs: 2
          uploadArtifacts: true
      - name: Print lighthouse score summary
        run: |
          echo "# Lighthouse score summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "| Metric | Scores |" >> $GITHUB_STEP_SUMMARY
          echo "| ------ | ------ |" >> $GITHUB_STEP_SUMMARY
          echo "${{ format('| Performance | {0} |', join(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary.performance), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ format('| Accessibility | {0} |', join(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary.accessibility), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ format('| Best Practices | {0} |', join(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary.best-practices), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ format('| SEO | {0} |', join(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary.seo), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ format('| PWA | {0} |', join(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary.pwa), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "~~~json" >> $GITHUB_STEP_SUMMARY
          echo '${{toJSON(fromJSON(steps.lighthouse-step.outputs.manifest).*.summary)}}' >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
